import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
//custom service to talk to the backend AI API
import { MistralService } from '../mistral.service';

//defining message body
interface Message {
  sender: 'user' | 'bot';
  content: string;
}

@Component({
  //component's custom HTML tag
  selector: 'app-chatbot',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './chatbot.component.html',
  styleUrls: ['./chatbot.component.css']
})
export class ChatbotComponent {
  // UI state
  isOpen = false;        // controls open/close of chat
  isTyping = false;      // shows "bot is typing"
  isRecording = false;   // mic state

  // Chat data
  //conversation history (array of Message)
  messages: Message[] = [
    { sender: 'bot', content: 'Hi! I am your AI Project Assistant ' }
  ];
  userInput = '';

  // Smart suggestions
  quickSuggestions: string[] = [
    "Summarize project status",
    "List my pending tasks",
    "Generate project report"
  ];

  // Microphone recording

  private mediaRecorder!: MediaRecorder;//built-in web API
  private audioChunks: Blob[] = [];

  //@types/dom-mediacapture-record
  constructor(private mistralService: MistralService) {}

  // Toggle chat open/close
  toggleChat() {
    this.isOpen = !this.isOpen;
  }

  // Send user message
  sendMessage(message?: string) {
    const input = message || this.userInput;
    //checks if input is empty if so returns
    if (!input.trim()) return;

    // Push user message
    this.messages.push({ sender: 'user', content: input });
    this.isTyping = true;

  // Call Mistral API
  this.mistralService.getChatCompletion(input, this.messages).subscribe({
    next: (reply: any) => {
      console.log('API Reply:', reply);  // Debug

      // Extract Mistral response text
      const botReply = reply?.choices?.[0]?.message?.content || ' No reply received';

      this.messages.push({ sender: 'bot', content: botReply });
      this.isTyping = false;
      //Saves the updated chat history to the browser's local storage
      localStorage.setItem('chatHistory', JSON.stringify(this.messages));
    },
    error: () => {
      this.messages.push({ sender: 'bot', content: 'Error connecting to server' });
      this.isTyping = false;
    }
  });



    this.userInput = '';
  }

  //  Start recording
  startRecording() {
    this.isRecording = true;
    // requesting an audio track
    navigator.mediaDevices.getUserMedia({ audio: true })
      //if granted
      .then(stream => {
        this.mediaRecorder = new MediaRecorder(stream);
        this.audioChunks = [];
        /*Collects all the individual audio chunks generated by
         the MediaRecorder as the recording progresse*/
        this.mediaRecorder.ondataavailable = event => {
          this.audioChunks.push(event.data);
        };

        this.mediaRecorder.onstop = () => {
          const audioBlob = new Blob(this.audioChunks, { type: 'audio/wav' });
          this.sendAudioToWhisper(audioBlob);
        };
        //starts the media recording process
        this.mediaRecorder.start();
      })
      .catch(err => {
        console.error('Microphone access denied', err);
        this.isRecording = false;
      });
  }

  // ⏹ Stop recording
  stopRecording() {
    this.isRecording = false;
    //checks if its recording ( prevent errors from non existent recorder)
    if (this.mediaRecorder && this.mediaRecorder.state !== 'inactive') {
      this.mediaRecorder.stop();
    }
  }

  // Send audio to Whisper backend
  private sendAudioToWhisper(audioBlob: Blob) {
    const formData = new FormData();
    formData.append('file', audioBlob, 'voice.wav');

    // URL of the backend endpoin
    fetch('http://localhost:3000/whisper', {
      //HTTP POST reques
      method: 'POST',
      body: formData
    })
      .then(async (res) => {
        if (!res.ok) {
          // If server responded with error JSON
          const errorData = await res.json().catch(() => ({}));
          throw new Error(
            `Server error ${res.status}: ${JSON.stringify(errorData, null, 2)}`
          );
        }
        return res.json();
      })
      .then((data) => {
        console.log("Whisper transcription:", data);

        this.userInput = data.text;  // put transcription in input
        this.sendMessage();           //  send automatically
      })
      .catch((err) => {
        console.error("Whisper request failed:", err.message || err);
        this.messages.push({
          sender: 'bot',
          content: `Whisper error: ${err.message || err}`
        });
      });
  }

}
